name: code check

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  PHPStan:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, xml, bcmath
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Run PHPStan (Larastan)
        run: |
          ./vendor/bin/phpstan analyse --memory-limit=512M

  Pint:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, xml, bcmath
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Run Laravel Pint
        run: |
          ./vendor/bin/pint --test

  PHPUnit:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: mbstring, xml, bcmath
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      - name: Run PHPUnit
        run: |
          php artisan test
